version: "3.9"

services:
        mysql:
                image: mysql:5.7
                container_name: mysql_db
                environment:
                        #using root/pwd file to provide simple security
                        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/pwdfile
                ports:
                        - "3308:3306"
                expose:
                        - '3306'
                volumes:
                        - /home/vagrant/mysql_data:/var/lib/mysql
                        #map folder with root/pwd file
                        - ./secrets:/run/secrets