# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento-ub2204-bb" # локальный basebox ubuntu2204
  config.vm.box_check_update = false

  config.vm.define "srv1" do |srv1|
    srv1.vm.provider "virtualbox" do |vb|
          vb.name = "vm_srv1_doker"
          vb.memory = "4096"
          vb.cpus = 4
        end
        
    srv1.vm.hostname = "srv1-doker"

    srv1.vm.provision "shell", path: "provision.sh"
    
    #srv1.vm.network "private_network", ip: "192.168.100.41" #, bridge: 'Intel(R) Dual Band Wireless-AC 3165'
    
    srv1.vm.network "public_network", ip: "192.168.50.41", bridge: 'Intel(R) Dual Band Wireless-AC 3165'

    srv1.vm.synced_folder "SyncFldr/", "/SyncFldr" 

  end

end
