- name: Ansible PB to Install Apache
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: install latest version of Apache on debian like OS
      apt: name=apache2 update_cache=yes state=latest
      when: ansible_os_family == "Debian"

    - name: install latest version of Apacheon on RedHat like OS
      yum: name=httpd update_cache=yes state=latest
      when: ansible_os_family == "RedHat"
 
    - name: copy index file
      template:
        src: "files/index-template.html"
        dest: "/var/www/html/index.html"
      notify: restart-apache
  
    - name: "UFW firewall allow HTTP on port {{ http_port }} on debian like OS"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
      when: ansible_os_family == "Debian"  
 
    - name: "UFW firewall allow HTTP on port {{ http_port }} on RedHat like OS"
      firewalld:
        port: "{{ http_port }}/tcp"
        permanent: yes
        state: enabled
      when: ansible_os_family == "RedHat"  

  handlers:
    - name: restart-apache
      service:
        name: "{{ service_name }}"
        state: restarted