---
# tasks file for RH-like
- name: install latest version of Apacheon on RedHat like OS
  yum: name=httpd update_cache=yes state=latest

- name: "UFW firewall allow HTTP on port {{ http_port }} on RedHat like OS"
  firewalld:
    port: "{{ http_port }}/tcp"
    permanent: yes
    state: enabled

- name: copy index file
  template:
    src: "index-template.j2"
    dest: "/var/www/html/index.html"
  notify: restart-apache